name: CI

on:
  push:
    branches:
      - raphael

jobs:
  checkout_and_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

  install_dependencies:
    runs-on: ubuntu-latest
    needs: checkout_and_setup
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          python -m unittest discover -s tests