name: CI

on:
  push:
    branches:
      - raphael

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install distutils
        run: sudo apt-get install python3-distutils
    
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pygame

    - name: Unit Tests
      run: |
        pytestpython -m unittest discover -s tests